### ISSUE TITLE
ValueError: Invalid RGBA argument: 'SystemButtonFace'

### ISSUE THREAD

**Issue by emilianozm24** [crpurcell/friendlyVRI#8]
I'm trying to run the program on Windows 10 with python 3.7 (and all the required modules except opencv), but running vriTk.py from the command prompt this doesn't cause anything and when I run it in an interactive IDLE Shell the beforementioned error pops up.

I don't know what it is I'm doing wrong or if there's something wrong with the installation. I'd appreciate your help!

Here the full error:

Traceback (most recent call last):
  File "C:\Users\Emiliano Zaldívar\friendlyVRI\vriTk.py", line 1544, in <module>
    app = App(root, bgColour).pack(side="top", fill="both", expand=True)
  File "C:\Users\Emiliano Zaldívar\friendlyVRI\vriTk.py", line 200, in __init__
    self.pltFrm = PlotFrame(self.dispWin, bgColour=self.bgColour)
  File "C:\Users\Emiliano Zaldívar\friendlyVRI\vriTk.py", line 1256, in __init__
    self.fig = Figure(figsize=(13.0, 8.0), facecolor=bgColour)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\figure.py", line 363, in __init__
    visible=frameon)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\patches.py", line 707, in __init__
    Patch.__init__(self, **kwargs)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\patches.py", line 82, in __init__
    self.set_facecolor(facecolor)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\patches.py", line 319, in set_facecolor
    self._set_facecolor(color)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\patches.py", line 307, in _set_facecolor
    self._facecolor = colors.to_rgba(color, alpha)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\colors.py", line 177, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "C:\Users\Emiliano Zaldívar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib\colors.py", line 233, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 'SystemButtonFace'

**Comment by crpurcell** [comment]
Hi, 

This seems to be a problem within the matplotlib plotting package when setting the figure facecolour. As a work-around you could try removing that argument from the line 

self.fig = Figure(figsize=(13.0, 8.0), facecolor=bgColour)

in vriTk.py. Note that I have not tested the code on Windows at all - only Mac and Linux - so you may encounter other problems. Good luck!

**Comment by emilianozm24** [comment]
> Hi,
> 
> This seems to be a problem within the matplotlib plotting package when setting the figure facecolour. As a work-around you could try removing that argument from the line
> 
> self.fig = Figure(figsize=(13.0, 8.0), facecolor=bgColour)
> 
> in vriTk.py. Note that I have not tested the code on Windows at all - only Mac and Linux - so you may encounter other problems. Good luck!

Thanks, this worked!!

**Comment by Totrasmek** [comment]
I have made a pull request for this issue.
